# Generated by Django 5.2.11 on 2026-02-14 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Utilisateur', 'verbose_name_plural': 'Utilisateurs'},
        ),
        migrations.AddField(
            model_name='user',
            name='user_service_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('candidat', 'Candidat'), ('commission', 'Commission'), ('secretaire', 'Secrétaire Général'), ('directeur', 'Directeur'), ('gestionnaire', 'Gestionnaire de Compte')], default='candidat', max_length=20),
        ),
    ]
