# Generated by Django 5.2.11 on 2026-02-14 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_alter_user_options_user_user_service_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_inscription'], 'verbose_name': 'Utilisateur', 'verbose_name_plural': 'Utilisateurs'},
        ),
        migrations.AlterField(
            model_name='user',
            name='date_inscription',
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription"),
        ),
        migrations.AlterField(
            model_name='user',
            name='derniere_connexion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dernière connexion'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('candidat', 'Candidat'), ('commission', 'Commission'), ('admin', 'Administrateur'), ('directeur', 'Directeur'), ('secretaire_general', 'Secrétaire Général')], default='candidat', max_length=30, verbose_name='Rôle'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_service_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID User Service'),
        ),
    ]
