# Generated by Django 6.0.2 on 2026-02-24 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_user_id', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('cin', models.CharField(max_length=8, unique=True)),
                ('telephone', models.CharField(max_length=20)),
                ('date_naissance', models.DateField()),
                ('moyenne_l1', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('moyenne_l2', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('moyenne_l3', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('moyenne_generale', models.DecimalField(decimal_places=2, max_digits=4)),
                ('moyenne_bac', models.DecimalField(decimal_places=2, max_digits=4)),
                ('type_candidature', models.CharField(choices=[('master', 'Master'), ('ingenieur', 'Cycle Ingénieur')], max_length=10)),
                ('voeux', models.JSONField(blank=True, null=True)),
                ('specialite', models.CharField(blank=True, max_length=50, null=True)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('en_attente', 'En attente de validation'), ('validee', 'Validée'), ('rejetee', 'Rejetée'), ('preselectionne', 'Présélectionné')], default='en_cours', max_length=20)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('classement', models.IntegerField(blank=True, null=True)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('date_limite_modification', models.DateTimeField(blank=True, null=True)),
                ('commentaire_rejet', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'candidatures',
                'ordering': ['-date_soumission'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('cin', 'CIN'), ('releves_l1', 'Relevés L1'), ('releves_l2', 'Relevés L2'), ('releves_l3', 'Relevés L3'), ('diplome', 'Diplôme'), ('photo', "Photo d'identité"), ('cv', 'CV'), ('lettre_motivation', 'Lettre de motivation')], max_length=20)),
                ('fichier_nom', models.CharField(max_length=255)),
                ('fichier_path', models.FileField(upload_to='documents/')),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('statut_verification', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('rejete', 'Rejeté')], default='en_attente', max_length=15)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('candidature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='candidature_app.candidature')),
            ],
            options={
                'db_table': 'documents',
            },
        ),
    ]
